# Generated by Django 2.1.2 on 2019-12-12 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='name',
            new_name='type',
        ),
    ]
