# Generated by Django 2.1.2 on 2020-01-26 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_posts'),
        ('qna', '0002_auto_20191223_1659'),
    ]

    operations = [

    ]
