# Generated by Django 2.1.2 on 2020-01-26 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_posts_status'),
        ('qna', '0003_auto_20200126_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.Posts'),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer_details',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer_type',
            field=models.CharField(choices=[('objective', 'objective'), ('full_length', 'full_length'), ('radio_button', 'radio_button')], default=2, max_length=200),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('adopter', 'adopter'), ('poster', 'poster')], default=1, max_length=200),
        ),
    ]
